Singly linked list
zigcc/zig-cookbook pull request #47
Opened 2024-02-29 18:09 UTC by CodingAndTechnology

I have added a simple singly linked list example (12-02) under 'Data Structures' Section. Please check if the example can be added in Zig cookbook. Thank you!

2024-03-01 13:07 UTC, jiacai2050 commented
Hi, thanks for contribution.

It seems the CI failed due to style issue, did you execute `zig fmt`?

2024-03-01 13:21 UTC, CodingAndTechnology commented
Appreciated your help, thanks a lot. I just executed zig fmt.

2024-03-01 15:49 UTC, jiacai2050 requested changes

2024-03-01 15:49 UTC, jiacai2050 commented on src/12-02.zig
> +            }
```suggestion
            while (head.next) |h| {
                head = h.next;
            }
            
            head.next = node;

```

2024-03-01 15:49 UTC, jiacai2050 commented on src/12-02.zig
> +
```suggestion
```

2024-03-01 15:49 UTC, jiacai2050 commented on src/12-02.zig
> +                    found = true;
return true directly.

2024-03-01 15:49 UTC, jiacai2050 commented on src/12-02.zig
> +            var node = self.root;
```suggestion
            var head = self.root;
```

Keep variable name same with other functions.

2024-03-01 17:32 UTC, CodingAndTechnology commented on src/12-02.zig
> +            }
Previous code is more readable and in sync with other code places and the suggested code errors out so want to continue with the previous code.

2024-03-01 17:36 UTC, CodingAndTechnology commented
Thanks for your suggestions. Most of them are done and the code works fine. Please let me know if this works.

2024-03-02 02:24 UTC, jiacai2050 approved these changes
LGTM

2024-03-02 02:24 UTC, merged